server:
  port: 9004

spring:
  application:
    name: RegisterLogin-service
  datasource:
    url: jdbc:mysql://localhost:3306/loan_payment?createDatabaseIfNotExist=true
    username: root
    password: jaanu123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: Xyza@123
  expiration: 3600000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
