server:
  port: 8765

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: personalLoanDocsUpload_route
          uri: "lb://personalLoanDoc-service"
          predicates:
            - Path=/api/v1/loan/personal/docs/**

        - id: otp_route
          uri: "lb://otp-service"
          predicates:
            - Path=/api/v1/otp/**

        - id: loanService_route
          uri: "lb://loanInfo-service"
          predicates:
            - Path=/api/v1/**

#        - id: goldloanService_route
#          uri: "lb://GoldLoan_service"
#          predicates:
#           - Path=/api/v1/loan/gold/docs/**