server:
  port: 9008
spring:
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/regd_users_db?createDatabaseIfNotExist=true
  #    username: root
  #    password: root
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: HomeLoan_Service
  data:
    mongodb:
      database: homeLoanDocs_DB
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

