server:
  port: 9010

spring:
  application:
    name: personalLoanDoc-service

  data:
    mongodb:
      database: personalLoanDocs_DB
      host: localhost
      port: 27017

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

